# Generated by Django 5.2.5 on 2025-08-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.EmailField(max_length=150)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=16)),
            ],
        ),
    ]
